---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-test1
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:15-el9
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: "admin"
        - name: POSTGRESQL_PASSWORD
          value: "password123" # Use Secrets for production!
        - name: POSTGRESQL_DATABASE
          value: "mydb"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/pgsql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
