---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
spec:
  storageClassName: lvms-vg1
  csi:
    driver: topolvm.io
    volumeHandle: 5f3358bd-3bad-4608-a687-72b6c969abc1
  provisioner: topolvm.io
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: postgres-pvc
    namespace: test1-webserver-db
  persistentVolumeReclaimPolicy: Delete

---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: postgres-pvc
    namespace: test1-webserver-db
  spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: lvms-vg1
    resources:
      requests:
        storage: 10Gi
    volumeName: postgres-data
    volumeMode: Filesystem